ServerEvents.recipes(event => {
  const LIST = [
    'easy_mob_farm:ocean_farm',
    'easy_mob_farm:pollen_trap_enhancement',
    'easy_mob_farm:sheep_enhancement',
    'easy_mob_farm:small_slot_upgrade',
    'easy_mob_farm:speed_enhancement',
    'easy_mob_farm:swamp_farm',
    'easy_mob_farm:sword_enhancement',
    'easy_mob_farm:tier0_mob_farm_template',
    'easy_mob_farm:tier1_mob_farm_template',
    'easy_mob_farm:tier2_mob_farm_template',
    'easy_mob_farm:tier3_mob_farm_template',
    'easy_mob_farm:void_binding_chain',
    'easy_mob_farm:animal_plains_farm',
    'easy_mob_farm:bee_hive_farm',
    'easy_mob_farm:big_slot_upgrade',
    'easy_mob_farm:blank_mob_capture_card',
    'easy_mob_farm:creative_blank_mob_capture_card',
    'easy_mob_farm:creative_mob_catcher',
    'easy_mob_farm:creative_mob_farm',
    'easy_mob_farm:creative_speed_enhancement',
    'easy_mob_farm:desert_farm',
    'easy_mob_farm:egg_collector_enhancement',
    'easy_mob_farm:enduring_capture_net',
    'easy_mob_farm:experience_enhancement',
    'easy_mob_farm:frog_catalyst_black_enhancement',
    'easy_mob_farm:frog_catalyst_blue_enhancement',
    'easy_mob_farm:frog_catalyst_brown_enhancement',
    'easy_mob_farm:frog_catalyst_cold_enhancement',
    'easy_mob_farm:frog_catalyst_cyan_enhancement',
    'easy_mob_farm:frog_catalyst_gray_enhancement',
    'easy_mob_farm:frog_catalyst_green_enhancement',
    'easy_mob_farm:frog_catalyst_light_blue_enhancement',
    'easy_mob_farm:frog_catalyst_light_gray_enhancement',
    'easy_mob_farm:frog_catalyst_lime_enhancement',
    'easy_mob_farm:frog_catalyst_magenta_enhancement',
    'easy_mob_farm:frog_catalyst_orange_enhancement',
    'easy_mob_farm:frog_catalyst_pink_enhancement',
    'easy_mob_farm:frog_catalyst_purple_enhancement',
    'easy_mob_farm:frog_catalyst_red_enhancement',
    'easy_mob_farm:frog_catalyst_temperate_enhancement',
    'easy_mob_farm:frog_catalyst_warm_enhancement',
    'easy_mob_farm:frog_catalyst_white_enhancement',
    'easy_mob_farm:frog_catalyst_yellow_enhancement',
    'easy_mob_farm:honey_extractor_enhancement',
    'easy_mob_farm:honey_harvester_frame_enhancement',
    'easy_mob_farm:iron_golem_farm',
    'easy_mob_farm:ironbound_containment_cage',
    'easy_mob_farm:jungle_farm',
    'easy_mob_farm:knife_enhancement',
    'easy_mob_farm:loot_enhancement',
    'easy_mob_farm:luck_enhancement',
    'easy_mob_farm:lucky_drop_farm',
    'easy_mob_farm:milk_bottle',
    'easy_mob_farm:milk_extractor_enhancement',
    'easy_mob_farm:mob_capture_card',
    'easy_mob_farm:monster_plains_cave_farm',
    'easy_mob_farm:mystic_binding_crystal',
    'easy_mob_farm:nether_fortress_farm',
    'easy_mob_farm:no_flowers_filter',
    'easy_mob_farm:no_meat_filter'
  ].map(s => s.toLowerCase())
  const SEEN = {}
  LIST.forEach(id => {
    if (!SEEN[id]) {
      SEEN[id] = true
      event.remove({ output: id })
    }
  })
})
